// 需要替换的正则表达式
const regulars = {
  commonjs: /static\/js\/public\/common\.js(\?v=\d+)?/g, // <script src="./static/js/public/common.js"></script>
  managejs: /static\/js\/manage\/manage\.js(\?v=\d+)?/g, // <script type="text/javascript" src="static/js/manage/manage.js"></script>
}

module.exports = {
  // html 文件的相对路径
  htmlPtah: [
    '../',
  ],
  // 需要替換的 js 文件
  replaceJs: [
    'utils.1.0.0.js',
    'common.js',
    'manage.js',
    'merchandise-common.js',
    'merchandise-drop.js',
    'pod.js',
    'pod-mes.js',
    'fuwusp.js',
    'merchandise-add.js',
    'merchandise-detail.js',
    'merchandise-package.js',
    'supplier-manage.js',
    'wa-WuLiu.js',
    'erp-purchase.js',
    'erp-warehouse.js',
    'erp-staff.js',
    'erp-customer.js',
    'purchase.js',
    'purchase_new.js',
    // 'erp-resident.js',
    'erp-finance.js',
    'erp_subscriber.js',
    'tixian.js',
    'joke.js',
    'cj_hot_issues.js',
    'erp-l.js',
    'erp-service.js',
    'erp-commodity-consult.js',
    'customer-store-order.js',
    'erp-czi-ord.js',
    'erp-zf-ord.js',
    'erp-cmu-ord.js',
    'erp-eall-ord.js',
    'erp-ecl-ord.js',
    'mycj.js',
    'excel-orders.js',
    'erp-sourcing.js',
    'erp-sourcedetail.js',
    'login.js',
    'mu-fone.js',
    'mu-one.js',
    'mu-two.js',
    'mu-three.js',
    'mu-four.js',
    'mu-chulizhong.js',
    'zi-two.js',
    'zi-three.js',
    'zi-four.js',
    'zi-five.js',
    'zi-all.js',
    'zi-diaodu.js',
    'log.js',
    'VideoOrder.js',
    'pod-ord.js',
    'staff-personcenter2.js',
    'systemSettings.js',
    'erpBank.js',
    'CommodityAnalysis.js',
    'SalesmanManagement.js',
    'analysis.js',
    'send-mail.js',
    'erpservice-send-mail.js',
    'zombie-order.js',
    'retention-order.js',
    'erp-zi-fulfil.js',
    'erp-l-order.js',
    'api.js',
    'api-storage.js',
    'utils.js',
    'filter.js',
    'register-success.js',
    'forgotPassword.js',
    'my-account.js',
    'register-success.js',
    'Download.js',
    'printPackingList.js',
    'staff-personcenter.js',
    'staff-personcenter2.js',
    'CommodityAnalysis/log.js',
    'chatlogin.js',
    'page.js',
    'cost.js',
    'mark.js',
    'pod-mark.js',
    'sign.js',
    'purchase-order.js',
    'receive.js',
    'receiving.js',
    'distribute.js',
    'index.js'
  ],
  // 需要替換的 css 文件
  replaceCss: [
    'common-boot4-part.css',
    'reset.css',
    'erp-public_style.css',
    'li_erp.css',
    'wa-erp.css',
    'merchandise-pod.css',
    'manage.css',
    'manage02.css',
    'merchandise.css',
    'erp-warehouse.css',
    'customer-store-order.css',
    'excel-orders.css',
    'customer-manage.css',
    'system-message.css',
    'gxh-gys.css',
    'erp-sourcing.css',
    'erp-sourcedetail.css',
    'mycj.css',
    'erp-home.css',
    'order-analysis.css',
    'chromeOrder.css',
    'excel-orders.css',
    'forgotPassword.css',
    'register-sucess.css'
  ],

  //# 更新组件中的 templateUrl
  routerjs: [
    '../static/js/manage/manage.js', // templateUrl
  ],
  routerjsRegExp: /templateUrl(\s+|\n+)?:(\s+|\n+)?['|"|`].+\.html(\?v=\d+)?['|"|`]/g,
  componentjs: [
    '../static/components',      // templateUrl
  ],
  //# templateUrl: './static/components/cart/cart.html?v=1562466179116'
  componentjsRegExp: /templateUrl(\s+|\n+)?:(\s+|\n+)?['|"|`].+\.html(\?v=\d+)?['|"|`]/,
  languageRegExp: /suffix(\n|\s)*:(\n|\s)*('|")\.json(\?v=\d+)?('|")/g, // 语言包后缀名
}