export const paymentType = {
	"订单-卡付款": 'Stripe',
	"订单-Checkout付款": 'Checkout',
	"转账-银行卡付款": "Wire Transfer",
	"订单-PayPal付款": "PayPal",
	"订单-Payeezy付款": "CJPay",
	"订单-余额付款": "Store Credit",
	"视频订单-余额付款": "Store Credit",
	"订单-Payssion付款": "Payssion",
	"COD订单-财务打款到cod商家钱包": "COD Order Collection",
	"余额扣款": "Balance Payment",
	"余额抵扣": "Balance Deduction",
	"库存抵扣": "Inventory Deduction",
	"等待-paypal确认到账": "Pending",
	"退款": "Refund",
	"DHL shipping cost": "DHL shipping cost",
	"payoneer": "Payoneer",
	"paypal": "Paypal",
	"stripe": "Stripe",
	"wire_transfer": "Wire Transfer",
	"订单-Payoneer付款": "Payoneer",
	"订单-退款": "Refund",
	"订单-GlobalAlipay付款": "Alipay",
	"订单-WeChatPay付款": "WeChat Pay",
	"余额-充值卡充值": "Gift Card",
}