// 忽略一些 js 文件，提升加载速度
exports.ignoreScripts = [
  'jquery-3.0.0.min.js',
  'jquery.min.js',
  'jqPaginator.js',
  'angular.min.js',
  'angular-sanitize.min.js',
  'angular-cookies.min.js',
  'angular-ui-router.min.js',
  'ocLazyLoad.min.js',
  'bootstrapValidator.min.js',
  'bootstrap.min.js',
  'layer.js',
  'wangEditor.min.js',
  'base64.min.js',
  'download.js',
  'swiper-3.4.2.jquery.min.js',
  'aliyun-upload-sdk-1.5.0.min.js',
  'es6-promise.min.js',
  'aliplayer-min.js',
  'md5.min.js',
  'jsencrypt.js',
  'securesdk_lzd_v1.js',
  'loading.js',
  'wui.min.js',
  'wui-date.js',
  'echarts.common.min.js',
  'WdatePicker.js',
  'angular-route.min.js',
  'angular-translate.min.js',
  'aliyun-oss-sdk-5.3.1.min.js',
  'google-sdk.js',
  'hello.js',
  'video.min.js',
  'html2canvas.min.js',
  'draggabilly.js',
  'jsencrypt.min.js',
  'bootstrap-select.min.js',
  'hello.all.min.js',
];

// 忽略一些 css 文件，提升加载速度
exports.ignoreLinks = [
  'bootstrap.min.css',
  'bootstrapValidator.min.css',
  'swiper-3.4.2.min.css',
  'loading.css',
  'wangEditor.min.css',
  'aliplayer-min.css',
  'wui.min.css',
  'dcalendar.picker.css',
  'dcalendar.picker.css',
  'bootstrap-select.min.css',
];
